// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBoletimTransporteDigital.Data;

#nullable disable

namespace SistemaBoletimTransporteDigital.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240514011722_CriarBd")]
    partial class CriarBd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.CorridaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFinalCorrida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioCorrida")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoCorrida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KmFinal")
                        .HasColumnType("int");

                    b.Property<int>("KmInicial")
                        .HasColumnType("int");

                    b.Property<int?>("KmPercorrido")
                        .HasColumnType("int");

                    b.Property<string>("LocalChegadaCorrida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalSaidaCorrida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusDaCorrida")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("VeiculoID");

                    b.ToTable("Corridas");
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.ManutencaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoDaImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorridaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoManutencao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoManutencao")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("VeiculoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("VeiculoID");

                    b.ToTable("Manutencoes");
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CodigoFuncional")
                        .HasColumnType("int");

                    b.Property<int?>("CorridaStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("EstaVinculadoAumaCorrida")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Celular = "11912345678",
                            CodigoFuncional = 0,
                            CorridaStatus = 4,
                            DataCriacao = new DateTime(2024, 5, 13, 22, 17, 21, 512, DateTimeKind.Local).AddTicks(4289),
                            DataUltimaAtualizacao = new DateTime(2024, 5, 13, 22, 17, 21, 512, DateTimeKind.Local).AddTicks(4290),
                            Email = "julioduartebatista753@gmail.com",
                            EstaVinculadoAumaCorrida = 6,
                            Nome = "admin",
                            Perfil = 1,
                            Senha = "d033e22ae348aeb5660fc2140aec35850c4da997",
                            Usuario = "ADMIN"
                        });
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("CadastroSistema")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CarroEmUso")
                        .HasColumnType("int");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prefixo")
                        .HasColumnType("int");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.Property<string>("Veiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VinculadoCarroAcorrida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.CorridaModel", b =>
                {
                    b.HasOne("SistemaBoletimTransporteDigital.Models.UsuarioModel", "Usuario")
                        .WithMany("Corridas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBoletimTransporteDigital.Models.VeiculoModel", "Veiculo")
                        .WithMany("Corridas")
                        .HasForeignKey("VeiculoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.ManutencaoModel", b =>
                {
                    b.HasOne("SistemaBoletimTransporteDigital.Models.UsuarioModel", "Usuario")
                        .WithMany("Manutencoes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBoletimTransporteDigital.Models.VeiculoModel", "Veiculo")
                        .WithMany("Manutencoes")
                        .HasForeignKey("VeiculoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.UsuarioModel", b =>
                {
                    b.Navigation("Corridas");

                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("SistemaBoletimTransporteDigital.Models.VeiculoModel", b =>
                {
                    b.Navigation("Corridas");

                    b.Navigation("Manutencoes");
                });
#pragma warning restore 612, 618
        }
    }
}
